version: '3'

services:
  # start the db image and map to port 27017
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports: [27017:27017]
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./logs:/var/log/mongod/
      - ./db:/var/lib/mongodb

  app:
    # start up the web app image and map to localhost
    container_name: app
    build: ./app
    restart: always
    ports: [80:3000]
    # set variable for a db port
    environment:
      - DB_HOST=mongodb://mongo:27017/posts
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
    - ./app:/src/app
    # could also use links
    # can run the seeds here if CMD doesn't work
     
    
volumes:
  data-volume:

  
